#front용 설정
server:
  port: 80
   
baseurl: http://localhost/
tokenlength: 8


# api용 설정 
api:
  shorturl: http://localhost/shorturl

aws:
  accessKeyId: xxxx
  secretAccessKey: xxxx
  region: us-east-1
  dynamodb:
    endpoint: dynamodb.us-east-1.amazonaws.com
